version: '3.3'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=vending
      - POSTGRES_PASSWORD=vending
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: